sudo: required
services: 
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t anavarron/docker-react

script:
  - docker run -e CI=true anavarron/docker-react npm run test -- --coverage

